// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using timefree_training_ticketing.Models.EF.Ticketing;

#nullable disable

namespace timefree_training_ticketing.Migrations
{
    [DbContext(typeof(Ticketing))]
    partial class TicketingModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("timefree_training_ticketing.Models.EF.Ticketing.order", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("_deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("created_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("created_by_ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("date_created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("date_modified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("modified_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("modified_by_ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("price")
                        .HasColumnType("int");

                    b.Property<int?>("quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ticket_guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("user_guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("guid")
                        .HasName("PK__order__497F6CB4C4F04505");

                    b.HasIndex("ticket_guid");

                    b.HasIndex("user_guid");

                    b.ToTable("order", "ticketing-system");
                });

            modelBuilder.Entity("timefree_training_ticketing.Models.EF.Ticketing.ticket", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("_deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("created_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("created_by_ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("date_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("event_name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("modified_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("modified_by_ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("price")
                        .HasColumnType("int");

                    b.Property<string>("ticket_type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("guid")
                        .HasName("PK__ticket__497F6CB4E07C527F");

                    b.ToTable("ticket", "ticketing-system");
                });

            modelBuilder.Entity("timefree_training_ticketing.Models.EF.Ticketing.user", b =>
                {
                    b.Property<Guid>("guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("_deleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("created_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("created_by_ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("date_created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTime?>("date_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("first_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("last_name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("modified_by")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("modified_by_ip")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("guid")
                        .HasName("PK__users__497F6CB44F81FB5C");

                    b.ToTable("user", "ticketing-system");
                });

            modelBuilder.Entity("timefree_training_ticketing.Models.EF.Ticketing.order", b =>
                {
                    b.HasOne("timefree_training_ticketing.Models.EF.Ticketing.ticket", "ticket")
                        .WithMany("order")
                        .HasForeignKey("ticket_guid")
                        .HasConstraintName("FK_order_ticket");

                    b.HasOne("timefree_training_ticketing.Models.EF.Ticketing.user", "user")
                        .WithMany("order")
                        .HasForeignKey("user_guid")
                        .HasConstraintName("FK_order_user");

                    b.Navigation("ticket");

                    b.Navigation("user");
                });

            modelBuilder.Entity("timefree_training_ticketing.Models.EF.Ticketing.ticket", b =>
                {
                    b.Navigation("order");
                });

            modelBuilder.Entity("timefree_training_ticketing.Models.EF.Ticketing.user", b =>
                {
                    b.Navigation("order");
                });
#pragma warning restore 612, 618
        }
    }
}
